.PHONY: all clean

all:
	$(MAKE) -C vanLeer
	$(MAKE) -C tvdLimitedCubicUpwindCPCFit
	$(MAKE) -C snapMesh

clean:
	$(MAKE) -C vanLeer clean
	$(MAKE) -C tvdLimitedCubicUpwindCPCFit clean
	$(MAKE) -C snapMesh clean
